CC=gcc
CFLAGS= -g -O3 -march=native
LDLIBS=-lm -lIL

sobel: sobel.c

blur: blur.c

emboss: emboss.c

erode: erode.c

dilate: dilate.c

grayscale: grayscale.c

.PHONY: clean

clean:
	rm sobel blur emboss erode dilate grayscale *.jpg
